export interface VietnamBank {
  code: string;
  name: string;
  shortName: string;
}

export const VIETNAM_BANKS: VietnamBank[] = [
  { code: "VCB", name: "Ngân hàng TMCP Ngoại thương Việt Nam", shortName: "Vietcombank" },
  { code: "TCB", name: "Ngân hàng TMCP Kỹ thương Việt Nam", shortName: "Techcombank" },
  { code: "VPB", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", shortName: "VPBank" },
  { code: "MBB", name: "Ngân hàng TMCP Quân đội", shortName: "MB Bank" },
  { code: "ACB", name: "Ngân hàng TMCP Á Châu", shortName: "ACB" },
  { code: "BID", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam", shortName: "BIDV" },
  { code: "CTG", name: "Ngân hàng TMCP Công thương Việt Nam", shortName: "VietinBank" },
  { code: "AGR", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn", shortName: "Agribank" },
  { code: "SHB", name: "Ngân hàng TMCP Sài Gòn – Hà Nội", shortName: "SHB" },
  { code: "STB", name: "Ngân hàng TMCP Sài Gòn Thương Tín", shortName: "Sacombank" },
  { code: "HDB", name: "Ngân hàng TMCP Phát triển TP.HCM", shortName: "HDBank" },
  { code: "TPB", name: "Ngân hàng TMCP Tiên Phong", shortName: "TPBank" },
  { code: "MSB", name: "Ngân hàng TMCP Hàng Hải Việt Nam", shortName: "MSB" },
  { code: "LPB", name: "Ngân hàng TMCP Bưu điện Liên Việt", shortName: "LienVietPostBank" },
  { code: "OCB", name: "Ngân hàng TMCP Phương Đông", shortName: "OCB" },
  { code: "EIB", name: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam", shortName: "Eximbank" },
  { code: "SSB", name: "Ngân hàng TMCP Đông Nam Á", shortName: "SeABank" },
  { code: "NAB", name: "Ngân hàng TMCP Nam Á", shortName: "Nam A Bank" },
  { code: "BAB", name: "Ngân hàng TMCP Bắc Á", shortName: "Bac A Bank" },
  { code: "VAB", name: "Ngân hàng TMCP Việt Á", shortName: "VietABank" },
  { code: "SCB", name: "Ngân hàng TMCP Sài Gòn", shortName: "SCB" },
  { code: "ABB", name: "Ngân hàng TMCP An Bình", shortName: "ABBank" },
  { code: "KLB", name: "Ngân hàng TMCP Kiên Long", shortName: "KienLongBank" },
  { code: "PGB", name: "Ngân hàng TMCP Xăng dầu Petrolimex", shortName: "PGBank" },
  { code: "VIB", name: "Ngân hàng TMCP Quốc tế Việt Nam", shortName: "VIB" },
  { code: "NVB", name: "Ngân hàng TMCP Quốc Dân", shortName: "NCB" },
  { code: "SGB", name: "Ngân hàng TMCP Sài Gòn Công Thương", shortName: "SaigonBank" },
  { code: "PVC", name: "Ngân hàng TMCP Đại Chúng Việt Nam", shortName: "PVcomBank" },
  { code: "BVB", name: "Ngân hàng TMCP Bảo Việt", shortName: "BaoVietBank" },
  { code: "VRB", name: "Ngân hàng Liên doanh Việt - Nga", shortName: "VRB" },
  { code: "GPB", name: "Ngân hàng TM TNHH MTV Dầu Khí Toàn Cầu", shortName: "GPBank" },
  { code: "CBB", name: "Ngân hàng TM TNHH MTV Xây dựng Việt Nam", shortName: "CB Bank" },
  { code: "OJB", name: "Ngân hàng TM TNHH MTV Đại Dương", shortName: "OceanBank" },
  { code: "CAKE", name: "Ngân hàng Số CAKE by VPBank", shortName: "CAKE" },
  { code: "UBANK", name: "Ngân hàng Số Ubank by VPBank", shortName: "Ubank" },
  { code: "TNEX", name: "Ngân hàng Số TNEX by MSB", shortName: "TNEX" },
  { code: "CIMB", name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB" },
  { code: "SCVN", name: "Ngân hàng TNHH MTV Standard Chartered VN", shortName: "Standard Chartered" },
  { code: "HSBC", name: "Ngân hàng TNHH MTV HSBC Việt Nam", shortName: "HSBC" },
  { code: "SHBVN", name: "Ngân hàng TNHH MTV Shinhan Việt Nam", shortName: "Shinhan Bank" },
  { code: "WOO", name: "Ngân hàng TNHH MTV Woori Việt Nam", shortName: "Woori Bank" },
  { code: "UOB", name: "Ngân hàng TNHH MTV UOB Việt Nam", shortName: "UOB" },
  { code: "KBVN", name: "Ngân hàng TNHH MTV KB Kookmin Việt Nam", shortName: "KB Bank" },
  { code: "IBKVN", name: "Ngân hàng Công nghiệp Hàn Quốc - CN HN", shortName: "IBK" },
  { code: "PNLVN", name: "Ngân hàng TNHH MTV Public Bank Việt Nam", shortName: "Public Bank" },
  { code: "HLBVN", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", shortName: "Hong Leong" },
];
